# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/OSDZU3_HardwarePlatform_IO_Standards.xdc

# TCL: imports/new/osdzu3_helper.tcl

# TCL: imports/new/osdzu3_package_pins.tcl

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_0 || ORIG_REF_NAME==design_1_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_0_1/design_1_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_1 || ORIG_REF_NAME==design_1_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_0/design_1_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_9_0/design_1_axi_gpio_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_9_0 || ORIG_REF_NAME==design_1_axi_gpio_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_10_0/design_1_util_ds_buf_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_10_0 || ORIG_REF_NAME==design_1_util_ds_buf_10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_12_0/design_1_util_ds_buf_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_12_0 || ORIG_REF_NAME==design_1_util_ds_buf_12_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_10_0/design_1_axi_gpio_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_10_0 || ORIG_REF_NAME==design_1_axi_gpio_10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_14_0/design_1_util_ds_buf_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_14_0 || ORIG_REF_NAME==design_1_util_ds_buf_14_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_14_1/design_1_util_ds_buf_14_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_14_1 || ORIG_REF_NAME==design_1_util_ds_buf_14_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_4_0 || ORIG_REF_NAME==design_1_axi_gpio_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_4_0/design_1_util_ds_buf_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_4_0 || ORIG_REF_NAME==design_1_util_ds_buf_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_7_0/design_1_util_ds_buf_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_7_0 || ORIG_REF_NAME==design_1_util_ds_buf_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_4_1/design_1_axi_gpio_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_4_1 || ORIG_REF_NAME==design_1_axi_gpio_4_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_4_1/design_1_util_ds_buf_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_4_1 || ORIG_REF_NAME==design_1_util_ds_buf_4_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_7_1/design_1_util_ds_buf_7_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_7_1 || ORIG_REF_NAME==design_1_util_ds_buf_7_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_4_2/design_1_axi_gpio_4_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_4_2 || ORIG_REF_NAME==design_1_axi_gpio_4_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_4_2/design_1_util_ds_buf_4_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_4_2 || ORIG_REF_NAME==design_1_util_ds_buf_4_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_7_2/design_1_util_ds_buf_7_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_7_2 || ORIG_REF_NAME==design_1_util_ds_buf_7_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_10_1/design_1_util_ds_buf_10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_10_1 || ORIG_REF_NAME==design_1_util_ds_buf_10_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_11_0/design_1_util_ds_buf_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_11_0 || ORIG_REF_NAME==design_1_util_ds_buf_11_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_2 || ORIG_REF_NAME==design_1_axi_gpio_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_quad_spi_0_1/design_1_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_1 || ORIG_REF_NAME==design_1_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_8_0/design_1_axi_gpio_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_8_0 || ORIG_REF_NAME==design_1_axi_gpio_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_6_0/design_1_util_ds_buf_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_6_0 || ORIG_REF_NAME==design_1_util_ds_buf_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/NYorr/Downloads/project_1/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
